export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  ONBOARDING: '/onboarding',
  BUSINESS_SETUP: '/business/setup',
  BUSINESS_PROFILE: '/business/profile',
  TEAM: '/team',
  PROFILE: '/profile',
  SUBSCRIPTION: '/subscription',
  DASHBOARD: '/dashboard',
  PRODUCTS: '/products',
  SCAN: '/scan',
  SALES: '/sales',
  PURCHASES: '/purchases',
  PARTIES: '/parties',
  TRANSACTIONS: '/transactions',
  NOTIFICATIONS: '/notifications',
  CUSTOMER_PURCHASES: '/my-purchases',
  CUSTOMER_CREDITS: '/my-credits',
  // Platform Admin - Isolated routes
  ADMIN_LOGIN: '/platform-admin/login',
  ADMIN_DASHBOARD: '/platform-admin/dashboard',
  ADMIN_BUSINESSES: '/platform-admin/businesses',
  ADMIN_USERS: '/platform-admin/users',
  ADMIN_SUBSCRIPTIONS: '/platform-admin/subscriptions',
  ADMIN_SETTINGS: '/platform-admin/settings',
  ADMIN_NOTIFICATIONS: '/platform-admin/notifications',
};
